# Generated by Django 4.0.3 on 2022-04-09 09:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_start', models.DateTimeField(verbose_name='Время и дата старта')),
                ('date_time_finish', models.DateTimeField(verbose_name='Время и дата конца')),
                ('text', models.TextField(max_length=300, verbose_name='Текст')),
                ('filter_info', models.CharField(max_length=25, verbose_name='Фильтр')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Телефон')),
                ('code_mob_opr', models.CharField(max_length=25, verbose_name='Код оператора')),
                ('teg', models.CharField(max_length=25, verbose_name='Тег')),
                ('time_zone', models.CharField(max_length=10, verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2022, 4, 9, 12, 18, 27, 673048), verbose_name='Дата создания/отправки')),
                ('success', models.BooleanField(default=False, verbose_name='Статус отправки')),
                ('mailing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_msg', to='mailing.mailings', verbose_name='Связанная рассылка')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_msg', to='mailing.users', verbose_name='Связанный пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
