# Generated by Django 4.0.3 on 2022-04-10 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 11, 10, 13, 590988), verbose_name='Дата создания/отправки'),
        ),
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='Телефон'),
        ),
    ]
