# Generated by Django 4.0.3 on 2022-04-10 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_messages_date_time_alter_users_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AddField(
            model_name='users',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 12, 2, 16, 820172), verbose_name='Дата создания/отправки'),
        ),
    ]
