# Generated by Django 4.0.3 on 2022-04-10 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_messages_last_update_users_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 12, 7, 34, 51877), verbose_name='Дата создания/отправки'),
        ),
    ]
