# Generated by Django 4.0.3 on 2022-04-10 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_users_active_alter_messages_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='mailing_id',
            new_name='mailing',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 12, 52, 58, 517770), verbose_name='Дата создания/отправки'),
        ),
    ]
