# Generated by Django 4.0.3 on 2022-04-13 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_rename_mailing_id_messages_mailing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 13, 36, 59, 499933), verbose_name='Дата создания/отправки'),
        ),
    ]
