# Generated by Django 4.0.3 on 2022-04-14 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_messages_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 14, 17, 22, 44, 676604), verbose_name='Дата создания/отправки'),
        ),
    ]
