# Generated by Django 4.0.3 on 2022-04-14 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_messages_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 14, 17, 23, 12, 374491), verbose_name='Дата создания/отправки'),
        ),
    ]
