# Generated by Django 4.0.3 on 2022-04-15 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_mailings_done_alter_messages_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 15, 16, 54, 7, 926736), verbose_name='Дата создания/отправки'),
        ),
    ]
