# Generated by Django 4.0.3 on 2022-04-17 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_alter_messages_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='mailing',
            new_name='mailing_text',
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 21, 41, 12, 820387), verbose_name='Дата создания/отправки'),
        ),
    ]
