# Generated by Django 4.0.3 on 2022-04-18 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_rename_mailing_messages_mailing_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 15, 5, 18, 599162), verbose_name='Дата создания/отправки'),
        ),
        migrations.AlterField(
            model_name='users',
            name='time_zone',
            field=models.CharField(max_length=30, verbose_name='Часовой пояс'),
        ),
    ]
